language: r
cache: packages
dist: trusty
latex: false
sudo: required

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
      brew_packages: jq
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - librdf0-dev
      - libv8-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
  
