# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: precise

apt_packages:
    - libv8-dev
    - librdf0-dev 

after_success:
  - Rscript -e 'covr::codecov()'


