sudo: required
services:
  - docker
script:
  - docker run -ti -v $(pwd):/home/rstudio/repo -w /home/rstudio/repo \
    rocker/verse \
    bash -c "apt-get update && apt-get -y install libjq-dev && R -e 'devtools::install(dep=TRUE); devtools::check()'"
    
